### ISSUE TITLE
error code 

### ISSUE THREAD

**Issue by diut-hua** [flyingshan/Learning-Polar-Encodings-For-Arbitrary-Oriented-Ship-Detection-In-SAR-Images#6]
Thanks for you code, when i eval the model, this error appears:
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    ctrbox_obj.evaluation(args, down_ratio=down_ratio)
  File "E:\Polar-master\eval.py", line 40, in evaluation

  File "E:\Polar-master\func_utils.py", line 97, in write_results
    pts0, scores0 = decode_prediction(predictions, dsets, args, img_id, down_ratio)
ValueError: too many values to unpack (expected 2)

This happens in the evaluation process too, can you give some suggestions?

**Comment by flyingshan** [comment]
Sorry, to visualize the bounding points, I made the function return them at [here](https://github.com/flyingshan/Learning-Polar-Encodings-For-Arbitrary-Oriented-Ship-Detection-In-SAR-Images/blob/842f9827b66b4e7d8b419648b353481567f5dd06/func_utils.py#L51), but I made some mistakes in cleaning the code.  I don't really have time testing and correcting it now, you may just try deleting 'bd_pts0' [here](https://github.com/flyingshan/Learning-Polar-Encodings-For-Arbitrary-Oriented-Ship-Detection-In-SAR-Images/blob/842f9827b66b4e7d8b419648b353481567f5dd06/func_utils.py#L51).

**Comment by diut-hua** [comment]
thank you for your reply!
but after i delete 'bd_pts0', there is another error appears:

Traceback (most recent call last):
  File "main.py", line 65, in <module>
    ctrbox_obj.evaluation(args, down_ratio=down_ratio)
  File "E:\Polar-master\eval.py", line 40, in evaluation
    func_utils.write_results(args,
  File "E:\Polar-master\func_utils.py", line 113, in write_results
    nms_results = non_maximum_suppression(pts_cat, scores_cat)
TypeError: non_maximum_suppression() missing 1 required positional argument: 'bd_pts'

Thansk a lot！

**Comment by kobezy** [comment]
I also encountered the same problem: ValueError: too many values to unpack (expected 2) How did you ultimately solve it?
